# prompts.py
import datetime

def get_filename(summary: str, suffix: str) -> str:
    # Shorten summary, remove spaces/special chars, add timestamp
    base = "_".join(summary.lower().split())[:20]
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{base}_{timestamp}.{suffix}"

PROMPTS = {
    'algebra_agent': {
        'instruction': (
            "# Algebra Animation Task\n"
            "+ Create a fun, visual 3D animation to explain the algebra problem, inspired by https://youtube.com/shorts/4W1rB64PCsY?si=wQ-E_-GdAOvSWoTr.\n"
            "+ Use stick figures, objects, or playful elements to make the concept engaging and easy to understand.\n"
            "+ Clearly show the step-by-step algebraic process (e.g., solving 1+1 visually).\n"
            "+ Use color, movement, and labels to highlight key steps.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step algebra solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'geometry_agent': {
        'instruction': (
            "# Geometry Animation Task\n"
            "+ Create a playful, clear 3D animation to explain the geometry concept, inspired by https://youtu.be/B1J6Ou4q8vE?si=UGXhW2659phSzM8a.\n"
            "+ Use fun shapes, colors, and movement to make the math visually appealing and memorable.\n"
            "+ Clearly show the geometric construction, transformation, or proof step by step.\n"
            "+ Add labels, highlights, and simple characters if helpful.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step geometry solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'calculus_agent': {
        'instruction': (
            "# Calculus Animation Task\n"
            "+ Make a dynamic, fun 3D animation to explain the calculus concept (e.g., derivatives, integrals, limits).\n"
            "+ Use moving objects, changing graphs, and playful elements to show how calculus works visually.\n"
            "+ Clearly illustrate the process (e.g., tangent line moving, area under curve growing).\n"
            "+ Use color, labels, and simple characters for clarity and engagement.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step calculus solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'trigonometry_agent': {
        'instruction': (
            "# Trigonometry Visualization Task\n"
            "+ Create a 3D animation of the unit circle, showing a rotating radius, the angle θ, and projections onto the x and y axes, similar to https://youtube.com/shorts/uV8rkuXl9Co?si=AB7vEdA1bqAmx5ZV, but in 3D.\n"
            "+ Use clear color coding for axes, circle, angle, and projections.\n"
            "+ Add labels for axes, angle, and coordinates.\n"
            "+ Animate the point moving around the circle and dynamically update projections and angle.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step trigonometry solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'linear_algebra_agent': {
        'instruction': (
            "# Linear Algebra Animation Task\n"
            "+ Make a 3D animation to visualize vectors, matrices, or transformations in a fun, clear way.\n"
            "+ Use arrows, grids, and playful elements to show how linear algebra works.\n"
            "+ Clearly show the process (e.g., vector addition, matrix transformation).\n"
            "+ Use color, movement, and labels for clarity.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step linear algebra solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'statistics_agent': {
        'instruction': (
            "# Statistics Animation Task\n"
            "+ Create a fun, visual 3D animation to explain the statistics concept (e.g., mean, median, probability).\n"
            "+ Use objects, characters, or playful elements to make the concept engaging and easy to understand.\n"
            "+ Clearly show the process step by step.\n"
            "+ Use color, movement, and labels for clarity.\n"
            "+ Use Blender 4.4+ Python API. Always set the render engine to 'BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', or 'CYCLES' (not 'BLENDER_EEVEE').\n"
            "+ Do not use deprecated or invalid render engine names.\n"
            "+ The Blender code must create at least one mesh, camera, and light, and animate at least one property (location, rotation, scale, or color) using keyframes.\n"
            "+ Add text or labels in the scene for clarity.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
            "+ Optionally, use Blender add-ons or plugins if they help visualize the math concept better.\n"
            "+ Ensure the animation is not empty and all objects are visible in the camera view.\n"
            "\n"
            "## Chain of Thought\n"
            "+ First, describe the step-by-step statistics solution.\n"
            "+ Next, outline a detailed animation plan in markdown, using + for each step.\n"
            "+ Then, save the animation plan as a .md file in animation_scripts.\n"
            "+ Finally, generate Blender Python code for the animation, save as a .py file in blender_scripts.\n"
            "+ Ensure all code is compatible with Blender 4.4.3 and does not use deprecated attributes.\n"
            "+ Keep filenames short, descriptive, and timestamped.\n"
            "+ The animation must visually and narratively explain the math solution, not just display objects.\n"
            "+ Use human-like or relatable characters, props, or scenes that act out the math process, making the solution intuitive and memorable.\n"
            "+ Use storytelling, humor, or real-world analogies where possible.\n"
            "+ The animation should visually demonstrate each step of the solution, not just the final answer.\n"
            "+ Synchronize the animation with the explanation, so viewers can see the math as it is solved.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name (e.g., `bpy.data.objects[\"Cube\"]`).\n"
        )
    },
    'animation_agent': {
        'instruction': (
            "# Animation Plan and Blender Code Generation\n"
            "+ Given a math solution and a creative animation idea, generate a detailed animation plan in markdown format.\n"
            "+ The plan must describe:\n"
            "  + All objects (e.g., user, car, ball, animals), their mesh types, and creative properties.\n"
            "  + Materials, color gradients, and textures for each object.\n"
            "  + Camera position, movement, and lens settings.\n"
            "  + Sunlight/lighting setup, including color, intensity, and direction.\n"
            "  + Any Blender add-ons or extra features to make the animation more realistic and fun.\n"
            "  + Step-by-step sequence of the animation, including creative/funny elements.\n"
            "+ Example: For x=2, y=3, animate a user flying to x=2 on the x-axis, drawing a thick, colorful line, then flying to y=3 on the y-axis with a different color gradient, making the animation exciting and visually appealing.\n"
            "+ Save the animation plan as a .md file in animation_scripts/ with a short, descriptive, timestamped filename.\n"
            "+ Then, generate Blender 4.4.3 compatible Python code for the animation, using all described objects, materials, and effects.\n"
            "+ Save the Blender code as a .py file in blender_scripts/ with a matching filename.\n"
            "+ Use creative mesh objects, materials, and Blender add-ons as needed.\n"
            "+ Ensure the animation is visually engaging, interactive, and fun.\n"
            "+ Do not use `bpy.context.active_object`. Instead, set the active object with `bpy.context.view_layer.objects.active = obj` or reference objects by name.\n"
            "+ Refer to the official Blender API documentation: https://docs.blender.org/api/current/index.html.\n"
        )
    },
}
